# Generated by Django 5.0.4 on 2024-06-04 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('photo', models.FileField(upload_to='Team photos')),
                ('post', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='projects photos')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publishedDate', models.DateField()),
                ('github', models.CharField(max_length=100)),
                ('paper', models.FileField(upload_to='topics file pdf')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='workshops photos')),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('organizer', models.ManyToManyField(to='contents.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.personne')),
                ('Workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.workshop')),
            ],
        ),
    ]
