# Generated by Django 5.0.4 on 2024-06-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='Workshop',
            new_name='workshop',
        ),
    ]
