# Generated by Django 5.0.4 on 2024-06-04 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_rename_workshop_conference_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.personne'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Team photos'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='topics file pdf'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='publishedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='workshops photos'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
