# Generated by Django 5.0.4 on 2024-06-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_conference_speaker_alter_conference_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
